export const ActionTypes = {
    SET_TAB: "SET_TAB",
    SET_NOTIFICATION: "SET_NOTIFICATION",
    REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
    SELECTED_TAB: "SELECTED_TAB",
    UNDO: "UNDO",
    REDO: "REDO"
}